"""empty message

Revision ID: f3d925843d81
Revises: 372ba530420f
Create Date: 2025-08-01 05:13:28.288716

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f3d925843d81'
down_revision = '372ba530420f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.drop_column('config')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.add_column(sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.alter_column('account_id',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###
