"""empty message

Revision ID: 372ba530420f
Revises: 010e38ec20f4
Create Date: 2025-07-24 11:23:02.590213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '372ba530420f'
down_revision = '010e38ec20f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
